### ISSUE TITLE
How to fix '0' problem

### ISSUE THREAD

**Issue by JeanGrenn** [caicre/PrivMRF#2]
After I setting up the enviroment and trying to run the code, I got this:

```
Traceback (most recent call last):
  File "/home/gyq/PrivMRF/script.py", line 54, in <module>
    run_experiment(data_list, method_list, exp_name, task='TVD', epsilon_list=epsilon_list, repeat=repeat, classifier_num=25)
  File "/home/gyq/PrivMRF/exp/evaluate.py", line 216, in run_experiment
    result = marginal_exp(data_list, method_list, exp_name, \
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyq/PrivMRF/exp/evaluate.py", line 362, in marginal_exp
    dp_data_list.append(run_syn(data_name, temp_exp_name, epsilon, task='TVD'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyq/PrivMRF/PrivMRF/main.py", line 178, in run_syn
    data_list = model.synthetic_data('./out/' + 'PrivMRF_'+ data_name + '_' + exp_name + '.csv')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyq/PrivMRF/PrivMRF/markov_random_field.py", line 996, in synthetic_data
    self.pandas_generate_cond_column_data(clique_marginal[clique], cond_attr, attr)
  File "/home/gyq/PrivMRF/PrivMRF/markov_random_field.py", line 1052, in pandas_generate_cond_column_data
    self.df = self.df.groupby(list(cond)).apply(foo)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyq/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 8252, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/gyq/miniconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 931, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/gyq/miniconda3/lib/python3.11/site-packages/pandas/core/groupby/grouper.py", line 975, in get_grouper
    obj._check_label_or_level_ambiguity(gpr, axis=axis)
  File "/home/gyq/miniconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 1735, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: '0' is both an index level and a column label, which is ambiguous.
```

Does anyone met the same problem?

**Comment by caicre** [comment]
Hi, thanks for your interest. I've updated the requirements.txt. You may try python3.7, cuda11.7 and reinstall all the requirements. Hopefully, it works now.
